# Generated by Django 4.1.7 on 2023-04-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do motorista')),
                ('cpf', models.CharField(max_length=11, verbose_name='Cpf do motorista')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone do motorista')),
                ('habilitacao', models.CharField(max_length=9, verbose_name='Habilitação do motorista')),
            ],
        ),
    ]
