# Generated by Django 4.1.7 on 2023-04-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca do carro')),
                ('placa', models.CharField(max_length=7, verbose_name='Placa do carro')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor do carro')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo do carro')),
                ('qtdPassageiros', models.IntegerField(max_length=1, verbose_name='Quantidade de passageiros')),
            ],
        ),
    ]
