# Generated by Django 4.1.7 on 2023-04-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='qtdPassageiros',
            field=models.IntegerField(verbose_name='Quantidade de passageiros'),
        ),
    ]
